### ISSUE TITLE
output piped to less is unusable

### ISSUE THREAD

**Issue by jose1711** [larsjsol/shellpic#11]
output ```shellpic image.jpg | less``` is not usable, unlike using this instead ```img2txt image.jpg | less```

**Comment by larsjsol** [comment]
Shellpic depends uses terminal escape sequences to set color and to move the cursor around when it draws images. Pagers and editors do not interpret these and only shows the unicode characters.

**Comment by jose1711** [comment]
please compare output of [chafa](https://github.com/hpjansson/chafa) which also makes use of escape sequences and `shellpic`:
```
convert -size 10x10 xc:red red.png
chafa -s 5x5 red.png | less  # this works fine
shellpic --scale-x 5 --scale-y 5 red.png | less  # this is broken (no linebreaks)
```
