### ISSUE TITLE
Python 3.7.2 has issue of "ModuleNotFoundError: No module named 'termios'"?

### ISSUE THREAD

**Issue by Huaweidev** [larsjsol/shellpic#12]
Python 3.7.2 has issue of "ModuleNotFoundError: No module named 'termios'"?

> D:\Program Files (x86)\Python\Python37-32\Scripts>python shellpic
Traceback (most recent call last):
  File "shellpic", line 16, in <module>
    from shellpic import *
  File "D:\Program Files (x86)\Python\Python37-32\lib\site-packages\shellpic\__init__.py", line 15, in <module>
    from shellpic.shell import *
  File "D:\Program Files (x86)\Python\Python37-32\lib\site-packages\shellpic\shell.py", line 16, in <module>
    import termios
ModuleNotFoundError: No module named 'termios'

> D:\Program Files (x86)\Python\Python37-32\Scripts>python -V
Python 3.7.2

**Comment by marado** [comment]
termios (and, as such, shellpic) only works on Unix systems:
https://docs.python.org/3/library/tty.html

**Comment by larsjsol** [comment]
As @marado said, shellpic does work on windows. Sorry.

**Comment by monsdar** [comment]
I think there's a missing `not` in your last comment. Just saying, as it confused me for a bit. (coming from google)
